### ISSUE TITLE
Could not start cocaine runtime

### ISSUE THREAD

**Issue by bioothod** [cocaine/cocaine-core#156]
User tries to setup cocaine cloud via habrhabr.ru tutorial:
https://groups.google.com/forum/#!topic/reverbrain/mUBYUYufU4s

Please send reply to maillist too

**Comment by bioothod** [comment]
Any progress on this issue?

**Comment by Kobolog** [comment]
It looks like the author found a workaround already.

**Comment by Kobolog** [comment]
Or do you want us to do something with CentOS packages? Should we summon ARKADY?

**Comment by noxiouz** [comment]
Step back! @tigro is coming!

**Comment by bioothod** [comment]
That workaround is quite ugly, looks like cocaine has hardcoded '/usr/lib' somewhere and doesn't take external libs into account. I wonder how this will work if I install package into custom directory

**Comment by noxiouz** [comment]
It's *hardcoded* in a default config.

**Comment by Kobolog** [comment]
The default value for the path to look for plugins is '/usr/lib', it's in the default configuration file, yeah.

**Comment by bioothod** [comment]
Does that mean it will work just if one replaces "paths" with correct suffix?
If so, please send a note to maillist about this 'fix'

**Comment by Kobolog** [comment]
Posted.

**Comment by Tigro** [comment]
I think on 64bit systems /usr/lib64 should be the default value. Yeah, 64bit Ubuntu also has this link on /usr/lib. So 'sed' this during the build.

**Comment by bioothod** [comment]
Thank you
