### ISSUE TITLE
cocaine does not start 

### ISSUE THREAD

**Issue by kazan417** [cocaine/cocaine-core#209]
version 0.12.3, ubuntu 14.04
after compiling i am trying to start, 
sudo service cocaine start and /usr/bin/cocaine-runtime -c /etc/cocaine/cocaine-default.conf 
 but cocaine write:
[Runtime] Parsing the configuration.
[Runtime] Initializing the logging system, backend: core.
and nothing more
ps aux | grep cocaine-runtime | grep -v grep give no results

**Comment by noxiouz** [comment]
Logs are written to syslog by defefault. Could you look up for them? I suggest, you would see something about multicast, but I'm not sure

**Comment by kazan417** [comment]
logs
unable to initialize the context - couldn't start 1 service(s): node: Invalid argument.
 initializing the core [source: core]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.912697] [E]: unable to load plugins: path '/usr/lib/cocaine' is not valid [source: core]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.912803] [I]: starting 4 execution unit(s) [source: core]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.913520] [I]: starting 4 service(s) [source: core]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.913851] [I]: restricting 1 service(s): locator [source: core, service: locator]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.913995] [I]: using 'multicast' as a cluster manager, enabling synchronization [source: core, service: locator]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.914204] [I]: joining multicast group '239.0.100.53:10053' [uuid: 87f51a6a-27c5-465d-a6d9-d8b27543f00b, source: core$
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.914491] [I]: using 'adhoc' as a gateway manager, enabling service routing [source: core, service: locator]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.915286] [I]: exposing service on local endpoint [::]:10053 [source: core, service: locator]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.916181] [I]: exposing service on local endpoint [::]:40847 [source: core, service: logging]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.916821] [E]: unable to initialize service: [1] component is not available [source: core, service: node]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.917078] [I]: exposing service on local endpoint [::]:41003 [source: core, service: storage]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.918735] [E]: emergency core shutdown [source: core]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.919570] [I]: removing service from local endpoint [::]:41003 [source: core, service: storage]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.919878] [I]: removing service from local endpoint [::]:40847 [source: core, service: logging]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.920136] [I]: removing service from local endpoint [::]:10053 [source: core, service: locator]
Jul 29 06:42:17 server2 cocaine[15862]: [2015-07-28 23:42:17.920980] [E]: unable to initialize the context - couldn't start 1 service(s): node: Invalid argument.
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.485245] [I]: initializing the server
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.491279] [I]: initializing the core [source: core]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.491584] [E]: unable to load plugins: path '/usr/lib/cocaine' is not valid [source: core]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.491689] [I]: starting 4 execution unit(s) [source: core]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.493380] [I]: starting 4 service(s) [source: core]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.493758] [I]: restricting 1 service(s): locator [source: core, service: locator]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.493899] [I]: using 'multicast' as a cluster manager, enabling synchronization [source: core, service: locator]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.494107] [I]: joining multicast group '239.0.100.53:10053' [uuid: 97bd8e78-6093-4358-822e-a7019694d624, source: core$
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.494424] [I]: using 'adhoc' as a gateway manager, enabling service routing [source: core, service: locator]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.495219] [I]: exposing service on local endpoint [::]:10053 [source: core, service: locator]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.496120] [I]: exposing service on local endpoint [::]:36251 [source: core, service: logging]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.496746] [E]: unable to initialize service: [1] component is not available [source: core, service: node]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.497008] [I]: exposing service on local endpoint [::]:45600 [source: core, service: storage]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.497572] [E]: emergency core shutdown [source: core]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.497898] [I]: removing service from local endpoint [::]:45600 [source: core, service: storage]
Jul 29 06:45:39 server2 cocaine[15879]: [2015-07-28 23:45:39.498200] [I]: removing service from local endpoint [::]:36251 [source: core, service: logging]

**Comment by noxiouz** [comment]
Oh, ```node``` plugin has been recently moved out from core to plugins: https://github.com/cocaine/cocaine-plugins/tree/v0.12-bleeding-edge. It should be built too.

Also the config must be patched a bit. Please, replace  ```"type": "node"``` with  ```"type": "node::v2"```

**Comment by kazan417** [comment]
thank you for fastest answer, i think it will help to me.
